/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import "./themedSplash";
import "./ipcCommands";
import "./appBadge";
import "./fixes";
import "./arrpc";
import "./patches/tray";
import "__patches__"; // auto generated by the build script

export * as Components from "./components";

import { openModal } from "@YouCord/types/utils";
import { onceReady } from "@YouCord/types/webpack";
import { React, VoiceActions } from "@YouCord/types/webpack/common";

import { SecurityModal } from "./components/SecurityModal";
import SettingsUi from "./components/settings/Settings";
import { VesktopLogger } from "./logger";
import { Settings } from "./settings";
export { Settings };

import type SettingsPlugin from "@YouCord/types/plugins/_core/settings";
import { VesktopSettingsIcon } from "shared/icons";

VesktopLogger.log("read if cute :3");
VesktopLogger.log(`YouCord v${VesktopNative.app.getVersion()}`);

const { customEntries, customSections } = Vencord.Plugins.plugins.Settings as any as typeof SettingsPlugin;

customEntries.push({
    key: "YouCord_YouCord_settings",
    title: "YouCord Settings",
    Component: SettingsUi,
    Icon: VesktopSettingsIcon
});

customSections.push(() => ({
    section: "YouCordSettings",
    label: "YouCord Settings",
    element: SettingsUi,
    className: "vc-YouCord-settings"
}));

VesktopNative.voice.onToggleSelfMute(() => VoiceActions.toggleSelfMute());
VesktopNative.voice.onToggleSelfDeaf(() => VoiceActions.toggleSelfDeaf());

// Afficher le SecurityModal uniquement au premier lancement
const SECURITY_MODAL_KEY = "youcord_security_modal_seen";
(onceReady as unknown as Promise<void>).then(() => {
    if (!localStorage.getItem(SECURITY_MODAL_KEY)) {
        setTimeout(() => {
            openModal(props => React.createElement(SecurityModal, props));
            localStorage.setItem(SECURITY_MODAL_KEY, "1");
        }, 1500);
    }
});

// TODO: remove this legacy workaround once some time has passed
if (!Vencord.Api.Styles.vencordRootNode) {
    const style = document.createElement("style");
    style.id = "vesktop-css-core";
    VesktopNative.app.getRendererCss().then(css => (style.textContent = css));
    document.addEventListener("DOMContentLoaded", () => document.documentElement.append(style), { once: true });
}
